
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace beta_clus_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 68> locations_array__ = 
{" (found before start of program)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 53, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 54, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 57, column 4 to column 41)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 60, column 4 to column 36)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 63, column 4 to column 29)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 69, column 4 to column 33)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 72, column 4 to column 38)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 79, column 4 to column 33)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 82, column 4 to column 30)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 83, column 4 to column 26)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 74, column 4 to column 41)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 77, column 8 to column 56)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 76, column 4 to line 77, column 56)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 89, column 4 to column 42)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 90, column 4 to column 38)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 91, column 4 to column 37)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 93, column 4 to column 30)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 96, column 8 to column 34)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 95, column 4 to line 96, column 34)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 99, column 8 to column 46)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 98, column 4 to line 99, column 46)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 102, column 8 to column 28)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 104, column 8 to column 66)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 101, column 18 to line 105, column 5)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 101, column 4 to line 105, column 5)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 4, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 5, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 6, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 7, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 9, column 10 to column 11)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 9, column 20 to column 21)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 9, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 10, column 10 to column 11)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 10, column 20 to column 21)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 10, column 22 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 10, column 4 to column 29)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 14, column 11 to column 14)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 14, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 15, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 18, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 18, column 4 to column 21)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 21, column 4 to column 26)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 22, column 4 to column 26)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 25, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 26, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 29, column 4 to column 27)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 30, column 4 to column 27)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 33, column 4 to column 13)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 36, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 37, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 39, column 10 to column 11)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 39, column 4 to column 13)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 42, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 42, column 13 to column 14)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 42, column 4 to column 22)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 47, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 47, column 14 to column 15)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 47, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 48, column 4 to column 34)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 60, column 10 to column 11)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 60, column 20 to column 23)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 63, column 10 to column 11)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 63, column 20 to column 21)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 72, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 72, column 13 to column 14)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 79, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/beta_clus.stan', line 79, column 13 to column 14)"};




class beta_clus_model final : public model_base_crtp<beta_clus_model> {

 private:
  int I;
  int T;
  int P;
  int H;
  std::vector<Eigen::Matrix<double, -1, 1>> y;
  std::vector<Eigen::Matrix<double, -1, -1>> X;
  Eigen::Matrix<double, -1, 1> mu_0_data__;
  double sigma_0;
  Eigen::Matrix<double, -1, 1> mu_w_1_data__;
  double a_alpha;
  double b_alpha;
  double a_tau2;
  double b_tau2;
  double a_sigma2;
  double b_sigma2;
  double rho;
  double a_xi;
  double b_xi;
  std::vector<int> s;
  Eigen::Matrix<double, -1, -1> inv_Q_data__;
  Eigen::Matrix<double, -1, -1> L_data__;
  int betas_clus_2dim__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mu_0{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mu_w_1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> inv_Q{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> L{nullptr, 0, 0};
 
 public:
  ~beta_clus_model() { }
  
  inline std::string model_name() const final { return "beta_clus_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = "};
  }
  
  
  beta_clus_model(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "beta_clus_model_namespace::beta_clus_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 26;
      context__.validate_dims("data initialization","I","int",
           std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      
      
      current_statement__ = 26;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 26;
      stan::math::check_greater_or_equal(function__, "I", I, 1);
      current_statement__ = 27;
      context__.validate_dims("data initialization","T","int",
           std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      
      
      current_statement__ = 27;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 27;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 28;
      context__.validate_dims("data initialization","P","int",
           std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      
      
      current_statement__ = 28;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 28;
      stan::math::check_greater_or_equal(function__, "P", P, 1);
      current_statement__ = 29;
      context__.validate_dims("data initialization","H","int",
           std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      
      
      current_statement__ = 29;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 29;
      stan::math::check_greater_or_equal(function__, "H", H, 1);
      current_statement__ = 30;
      stan::math::validate_non_negative_index("y", "I", I);
      current_statement__ = 31;
      stan::math::validate_non_negative_index("y", "T", T);
      current_statement__ = 32;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(T)});
      y = 
        std::vector<Eigen::Matrix<double, -1, 1>>(I, 
          Eigen::Matrix<double, -1, 1>::Constant(T,
            std::numeric_limits<double>::quiet_NaN()));
      
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 32;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 32;
        pos__ = 1;
        current_statement__ = 32;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 32;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 32;
            stan::model::assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", stan::model::index_uni(sym2__),
                                        stan::model::index_uni(sym1__));
            current_statement__ = 32;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 33;
      stan::math::validate_non_negative_index("X", "I", I);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("X", "T", T);
      current_statement__ = 35;
      stan::math::validate_non_negative_index("X", "P + 1", (P + 1));
      current_statement__ = 36;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(T), static_cast<size_t>((P + 1))});
      X = 
        std::vector<Eigen::Matrix<double, -1, -1>>(I, 
          Eigen::Matrix<double, -1, -1>::Constant(T, (P + 1),
            std::numeric_limits<double>::quiet_NaN()));
      
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 36;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 36;
        pos__ = 1;
        current_statement__ = 36;
        for (int sym1__ = 1; sym1__ <= (P + 1); ++sym1__) {
          current_statement__ = 36;
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            current_statement__ = 36;
            for (int sym3__ = 1; sym3__ <= I; ++sym3__) {
              current_statement__ = 36;
              stan::model::assign(X, X_flat__[(pos__ - 1)],
                "assigning variable X", stan::model::index_uni(sym3__),
                                          stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
              current_statement__ = 36;
              pos__ = (pos__ + 1);
            }
          }
        }
      }
      current_statement__ = 37;
      stan::math::validate_non_negative_index("mu_0", "P + 1", (P + 1));
      current_statement__ = 38;
      context__.validate_dims("data initialization","mu_0","double",
           std::vector<size_t>{static_cast<size_t>((P + 1))});
      mu_0_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant((P + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&mu_0) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mu_0_data__.data(), 
        (P + 1));
      
      {
        std::vector<local_scalar_t__> mu_0_flat__;
        current_statement__ = 38;
        mu_0_flat__ = context__.vals_r("mu_0");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= (P + 1); ++sym1__) {
          current_statement__ = 38;
          stan::model::assign(mu_0, mu_0_flat__[(pos__ - 1)],
            "assigning variable mu_0", stan::model::index_uni(sym1__));
          current_statement__ = 38;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 39;
      context__.validate_dims("data initialization","sigma_0","double",
           std::vector<size_t>{});
      sigma_0 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 39;
      sigma_0 = context__.vals_r("sigma_0")[(1 - 1)];
      current_statement__ = 40;
      stan::math::validate_non_negative_index("mu_w_1", "I", I);
      current_statement__ = 41;
      context__.validate_dims("data initialization","mu_w_1","double",
           std::vector<size_t>{static_cast<size_t>(I)});
      mu_w_1_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(I,
          std::numeric_limits<double>::quiet_NaN());
      new (&mu_w_1) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mu_w_1_data__.data(), I);
        
      
      {
        std::vector<local_scalar_t__> mu_w_1_flat__;
        current_statement__ = 41;
        mu_w_1_flat__ = context__.vals_r("mu_w_1");
        current_statement__ = 41;
        pos__ = 1;
        current_statement__ = 41;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 41;
          stan::model::assign(mu_w_1, mu_w_1_flat__[(pos__ - 1)],
            "assigning variable mu_w_1", stan::model::index_uni(sym1__));
          current_statement__ = 41;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 42;
      context__.validate_dims("data initialization","a_alpha","double",
           std::vector<size_t>{});
      a_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 42;
      a_alpha = context__.vals_r("a_alpha")[(1 - 1)];
      current_statement__ = 42;
      stan::math::check_greater_or_equal(function__, "a_alpha", a_alpha, 0);
      current_statement__ = 43;
      context__.validate_dims("data initialization","b_alpha","double",
           std::vector<size_t>{});
      b_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 43;
      b_alpha = context__.vals_r("b_alpha")[(1 - 1)];
      current_statement__ = 43;
      stan::math::check_greater_or_equal(function__, "b_alpha", b_alpha, 0);
      current_statement__ = 44;
      context__.validate_dims("data initialization","a_tau2","double",
           std::vector<size_t>{});
      a_tau2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 44;
      a_tau2 = context__.vals_r("a_tau2")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "a_tau2", a_tau2, 0);
      current_statement__ = 45;
      context__.validate_dims("data initialization","b_tau2","double",
           std::vector<size_t>{});
      b_tau2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 45;
      b_tau2 = context__.vals_r("b_tau2")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "b_tau2", b_tau2, 0);
      current_statement__ = 46;
      context__.validate_dims("data initialization","a_sigma2","double",
           std::vector<size_t>{});
      a_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 46;
      a_sigma2 = context__.vals_r("a_sigma2")[(1 - 1)];
      current_statement__ = 46;
      stan::math::check_greater_or_equal(function__, "a_sigma2", a_sigma2, 0);
      current_statement__ = 47;
      context__.validate_dims("data initialization","b_sigma2","double",
           std::vector<size_t>{});
      b_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 47;
      b_sigma2 = context__.vals_r("b_sigma2")[(1 - 1)];
      current_statement__ = 47;
      stan::math::check_greater_or_equal(function__, "b_sigma2", b_sigma2, 0);
      current_statement__ = 48;
      context__.validate_dims("data initialization","rho","double",
           std::vector<size_t>{});
      rho = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 48;
      rho = context__.vals_r("rho")[(1 - 1)];
      current_statement__ = 49;
      context__.validate_dims("data initialization","a_xi","double",
           std::vector<size_t>{});
      a_xi = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 49;
      a_xi = context__.vals_r("a_xi")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "a_xi", a_xi, 0);
      current_statement__ = 50;
      context__.validate_dims("data initialization","b_xi","double",
           std::vector<size_t>{});
      b_xi = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 50;
      b_xi = context__.vals_r("b_xi")[(1 - 1)];
      current_statement__ = 50;
      stan::math::check_greater_or_equal(function__, "b_xi", b_xi, 0);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("s", "I", I);
      current_statement__ = 52;
      context__.validate_dims("data initialization","s","int",
           std::vector<size_t>{static_cast<size_t>(I)});
      s = std::vector<int>(I, std::numeric_limits<int>::min());
      
      
      current_statement__ = 52;
      s = context__.vals_i("s");
      current_statement__ = 53;
      stan::math::validate_non_negative_index("inv_Q", "I", I);
      current_statement__ = 54;
      stan::math::validate_non_negative_index("inv_Q", "I", I);
      current_statement__ = 55;
      context__.validate_dims("data initialization","inv_Q","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(I)});
      inv_Q_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant(I, I,
          std::numeric_limits<double>::quiet_NaN());
      new (&inv_Q) Eigen::Map<Eigen::Matrix<double, -1, -1>>(inv_Q_data__.data(), I, I);
        
      
      {
        std::vector<local_scalar_t__> inv_Q_flat__;
        current_statement__ = 55;
        inv_Q_flat__ = context__.vals_r("inv_Q");
        current_statement__ = 55;
        pos__ = 1;
        current_statement__ = 55;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 55;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 55;
            stan::model::assign(inv_Q, inv_Q_flat__[(pos__ - 1)],
              "assigning variable inv_Q", stan::model::index_uni(sym2__),
                                            stan::model::index_uni(sym1__));
            current_statement__ = 55;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 56;
      stan::math::validate_non_negative_index("L", "I", I);
      current_statement__ = 57;
      stan::math::validate_non_negative_index("L", "I", I);
      current_statement__ = 58;
      L_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant(I, I,
          std::numeric_limits<double>::quiet_NaN());
      new (&L) Eigen::Map<Eigen::Matrix<double, -1, -1>>(L_data__.data(), I, I);
        
      
      current_statement__ = 59;
      stan::model::assign(L, stan::math::cholesky_decompose(inv_Q),
        "assigning variable L");
      current_statement__ = 60;
      stan::math::validate_non_negative_index("betas_clus", "H", H);
      current_statement__ = 61;
      betas_clus_2dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 61;
      betas_clus_2dim__ = (P + 1);
      current_statement__ = 61;
      stan::math::validate_non_negative_index("betas_clus", "P + 1",
                                              betas_clus_2dim__);
      current_statement__ = 62;
      stan::math::validate_non_negative_index("w_raw", "T", T);
      current_statement__ = 63;
      stan::math::validate_non_negative_index("w_raw", "I", I);
      current_statement__ = 64;
      stan::math::validate_non_negative_index("ws_tmp", "I", I);
      current_statement__ = 65;
      stan::math::validate_non_negative_index("ws_tmp", "T", T);
      current_statement__ = 66;
      stan::math::validate_non_negative_index("ws", "T", T);
      current_statement__ = 67;
      stan::math::validate_non_negative_index("ws", "I", I);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + 1 + (H * betas_clus_2dim__) + (T * I);
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "beta_clus_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 1;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      local_scalar_t__ tau2 = DUMMY_VAR__;
      current_statement__ = 2;
      tau2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ xi_constructor = DUMMY_VAR__;
      current_statement__ = 3;
      xi_constructor = in__.template read_constrain_lub<local_scalar_t__, 
                         jacobian__>(0, 1, lp__);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> betas_clus =
         std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(H, 
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
             betas_clus_2dim__, DUMMY_VAR__));
      current_statement__ = 4;
      betas_clus = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(H,
                     betas_clus_2dim__);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> w_raw =
         std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(T, 
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(I, DUMMY_VAR__));
      current_statement__ = 5;
      w_raw = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(T, I);
      local_scalar_t__ xi = DUMMY_VAR__;
      current_statement__ = 6;
      xi = ((2 * xi_constructor) - 1);
      Eigen::Matrix<local_scalar_t__, -1, -1> ws_tmp =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(I, T, DUMMY_VAR__);
      current_statement__ = 11;
      stan::model::assign(ws_tmp,
        stan::math::add(mu_w_1,
          stan::math::multiply(L,
            stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(1)))),
        "assigning variable ws_tmp", stan::model::index_min_max(1, I),
                                       stan::model::index_uni(1));
      current_statement__ = 13;
      for (int t = 2; t <= T; ++t) {
        current_statement__ = 12;
        stan::model::assign(ws_tmp,
          stan::math::add(
            stan::math::multiply(
              stan::model::deep_copy(
                stan::model::rvalue(ws_tmp, "ws_tmp",
                  stan::model::index_min_max(1, I),
                    stan::model::index_uni((t - 1)))), xi),
            stan::math::multiply(L,
              stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(t)))),
          "assigning variable ws_tmp", stan::model::index_min_max(1, I),
                                         stan::model::index_uni(t));
      }
      Eigen::Matrix<local_scalar_t__, -1, -1> ws =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(T, I, DUMMY_VAR__);
      current_statement__ = 8;
      stan::model::assign(ws, stan::math::transpose(ws_tmp),
        "assigning variable ws");
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 9;
      sigma = stan::math::sqrt(sigma2);
      local_scalar_t__ tau = DUMMY_VAR__;
      current_statement__ = 10;
      tau = stan::math::sqrt(tau2);
      {
        current_statement__ = 14;
        lp_accum__.add(
          stan::math::inv_gamma_lpdf<propto__>(sigma2, a_sigma2, b_sigma2));
        current_statement__ = 15;
        lp_accum__.add(
          stan::math::inv_gamma_lpdf<propto__>(tau2, a_tau2, b_tau2));
        current_statement__ = 16;
        lp_accum__.add(
          stan::math::beta_lpdf<propto__>(xi_constructor, a_xi, b_xi));
        current_statement__ = 17;
        lp_accum__.add(
          stan::math::normal_lpdf<propto__>(
            stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(1)),
            0, tau));
        current_statement__ = 19;
        for (int t = 2; t <= T; ++t) {
          current_statement__ = 18;
          lp_accum__.add(
            stan::math::normal_lpdf<propto__>(
              stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(t)),
              0, tau));
        }
        current_statement__ = 21;
        for (int h = 1; h <= H; ++h) {
          current_statement__ = 20;
          lp_accum__.add(
            stan::math::normal_lpdf<propto__>(
              stan::model::rvalue(betas_clus, "betas_clus",
                stan::model::index_uni(h)), mu_0, sigma_0));
        }
        current_statement__ = 25;
        for (int i = 1; i <= I; ++i) {
          int clus_i = std::numeric_limits<int>::min();
          current_statement__ = 22;
          clus_i = (stan::model::rvalue(s, "s", stan::model::index_uni(i)) +
                     1);
          current_statement__ = 23;
          lp_accum__.add(
            stan::math::normal_lpdf<propto__>(
              stan::model::rvalue(y, "y", stan::model::index_uni(i)),
              stan::math::add(
                stan::math::multiply(
                  stan::model::rvalue(X, "X", stan::model::index_uni(i)),
                  stan::model::rvalue(betas_clus, "betas_clus",
                    stan::model::index_uni(clus_i))),
                stan::model::rvalue(ws, "ws",
                  stan::model::index_min_max(1, T), stan::model::index_uni(i))),
              sigma));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "beta_clus_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double sigma2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      double tau2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      tau2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double xi_constructor = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 3;
      xi_constructor = in__.template read_constrain_lub<local_scalar_t__, 
                         jacobian__>(0, 1, lp__);
      std::vector<Eigen::Matrix<double, -1, 1>> betas_clus =
         std::vector<Eigen::Matrix<double, -1, 1>>(H, 
           Eigen::Matrix<double, -1, 1>::Constant(betas_clus_2dim__,
             std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 4;
      betas_clus = in__.template read<
                     std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(H,
                     betas_clus_2dim__);
      std::vector<Eigen::Matrix<double, -1, 1>> w_raw =
         std::vector<Eigen::Matrix<double, -1, 1>>(T, 
           Eigen::Matrix<double, -1, 1>::Constant(I,
             std::numeric_limits<double>::quiet_NaN()));
      current_statement__ = 5;
      w_raw = in__.template read<
                std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>>(T, I);
      double xi = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double, -1, -1> ws_tmp =
         Eigen::Matrix<double, -1, -1>::Constant(I, T,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, -1> ws =
         Eigen::Matrix<double, -1, -1>::Constant(T, I,
           std::numeric_limits<double>::quiet_NaN());
      double sigma = std::numeric_limits<double>::quiet_NaN();
      double tau = std::numeric_limits<double>::quiet_NaN();
      out__.write(sigma2);
      out__.write(tau2);
      out__.write(xi_constructor);
      for (int sym1__ = 1; sym1__ <= betas_clus_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          out__.write(betas_clus[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
          out__.write(w_raw[(sym2__ - 1)][(sym1__ - 1)]);
        }
      }
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 6;
      xi = ((2 * xi_constructor) - 1);
      current_statement__ = 11;
      stan::model::assign(ws_tmp,
        stan::math::add(mu_w_1,
          stan::math::multiply(L,
            stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(1)))),
        "assigning variable ws_tmp", stan::model::index_min_max(1, I),
                                       stan::model::index_uni(1));
      current_statement__ = 13;
      for (int t = 2; t <= T; ++t) {
        current_statement__ = 12;
        stan::model::assign(ws_tmp,
          stan::math::add(
            stan::math::multiply(
              stan::model::deep_copy(
                stan::model::rvalue(ws_tmp, "ws_tmp",
                  stan::model::index_min_max(1, I),
                    stan::model::index_uni((t - 1)))), xi),
            stan::math::multiply(L,
              stan::model::rvalue(w_raw, "w_raw", stan::model::index_uni(t)))),
          "assigning variable ws_tmp", stan::model::index_min_max(1, I),
                                         stan::model::index_uni(t));
      }
      current_statement__ = 8;
      stan::model::assign(ws, stan::math::transpose(ws_tmp),
        "assigning variable ws");
      current_statement__ = 9;
      sigma = stan::math::sqrt(sigma2);
      current_statement__ = 10;
      tau = stan::math::sqrt(tau2);
      if (emit_transformed_parameters__) {
        out__.write(xi);
        out__.write(ws_tmp);
        out__.write(ws);
        out__.write(sigma);
        out__.write(tau);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      sigma2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma2);
      local_scalar_t__ tau2 = DUMMY_VAR__;
      tau2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau2);
      local_scalar_t__ xi_constructor = DUMMY_VAR__;
      xi_constructor = in__.read<local_scalar_t__>();
      out__.write_free_lub(0, 1, xi_constructor);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> betas_clus =
         std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(H, 
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
             betas_clus_2dim__, DUMMY_VAR__));
      for (int sym1__ = 1; sym1__ <= betas_clus_2dim__; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          stan::model::assign(betas_clus, in__.read<local_scalar_t__>(),
            "assigning variable betas_clus", stan::model::index_uni(sym2__),
                                               stan::model::index_uni(sym1__));
        }
      }
      out__.write(betas_clus);
      std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>> w_raw =
         std::vector<Eigen::Matrix<local_scalar_t__, -1, 1>>(T, 
           Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(I, DUMMY_VAR__));
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
          stan::model::assign(w_raw, in__.read<local_scalar_t__>(),
            "assigning variable w_raw", stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
        }
      }
      out__.write(w_raw);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"sigma2", "tau2", "xi_constructor",
      "betas_clus", "w_raw", "xi", "ws_tmp", "ws", "sigma", "tau"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{}, std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(H),
                          static_cast<size_t>(betas_clus_2dim__)},
      std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(I)},
      std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(T)},
      std::vector<size_t>{static_cast<size_t>(T), static_cast<size_t>(I)},
      std::vector<size_t>{}, std::vector<size_t>{}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "tau2");
    param_names__.emplace_back(std::string() + "xi_constructor");
    for (int sym1__ = 1; sym1__ <= betas_clus_2dim__; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_clus" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "w_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "xi");
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ws_tmp" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ws" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "tau");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "tau2");
    param_names__.emplace_back(std::string() + "xi_constructor");
    for (int sym1__ = 1; sym1__ <= betas_clus_2dim__; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= H; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas_clus" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "w_raw" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "xi");
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ws_tmp" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
        {
          for (int sym2__ = 1; sym2__ <= T; ++sym2__) {
            {
              param_names__.emplace_back(std::string() + "ws" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
            } 
          }
        } 
      }
      param_names__.emplace_back(std::string() + "sigma");
      param_names__.emplace_back(std::string() + "tau");
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"xi_constructor\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas_clus\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(H) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(betas_clus_2dim__) + "}},\"block\":\"parameters\"},{\"name\":\"w_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(T) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "}},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"ws_tmp\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(T) + ",\"cols\":" + std::to_string(I) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"xi_constructor\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas_clus\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(H) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(betas_clus_2dim__) + "}},\"block\":\"parameters\"},{\"name\":\"w_raw\",\"type\":{\"name\":\"array\",\"length\":" + std::to_string(T) + ",\"element_type\":{\"name\":\"vector\",\"length\":" + std::to_string(I) + "}},\"block\":\"parameters\"},{\"name\":\"xi\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"ws_tmp\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(T) + "},\"block\":\"transformed_parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(T) + ",\"cols\":" + std::to_string(I) + "},\"block\":\"transformed_parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"tau\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + (H * betas_clus_2dim__)) + (T * I));
      const size_t num_transformed = emit_transformed_parameters * 
  ((((1 + (I * T)) + (T * I)) + 1) + 1);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  ((((1 + 1) + 1) + (H * betas_clus_2dim__)) + (T * I));
      const size_t num_transformed = emit_transformed_parameters * 
  ((((1 + (I * T)) + (T * I)) + 1) + 1);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 5> names__{"sigma2", "tau2",
      "xi_constructor", "betas_clus", "w_raw"};
      const std::array<Eigen::Index, 5> constrain_param_sizes__{1, 1, 
       1, (H * betas_clus_2dim__), (T * I)};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = beta_clus_model_namespace::beta_clus_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return beta_clus_model_namespace::profiles__;
}

#endif


