
// Code generated by stanc v2.30.1
#include <stan/model/model_header.hpp>
namespace dirichlet_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 84> locations_array__ = 
{" (found before start of program)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 47, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 48, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 49, column 4 to column 40)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 50, column 4 to column 21)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 51, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 52, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 53, column 4 to column 22)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 55, column 4 to column 36)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 59, column 4 to column 39)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 61, column 4 to column 22)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 64, column 4 to column 49)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 65, column 4 to column 52)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 67, column 4 to column 22)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 68, column 4 to column 61)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 69, column 4 to column 36)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 73, column 4 to column 37)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 74, column 4 to column 27)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 75, column 4 to column 43)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 76, column 4 to column 39)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 80, column 8 to column 53)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 79, column 19 to line 81, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 79, column 4 to line 81, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 85, column 12 to column 40)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 84, column 23 to line 86, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 84, column 8 to line 86, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 83, column 19 to line 87, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 83, column 4 to line 87, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 88, column 4 to column 51)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 92, column 8 to column 84)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 91, column 21 to line 93, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 91, column 8 to line 93, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 90, column 18 to line 94, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 90, column 4 to line 94, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 98, column 19 to column 20)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 98, column 12 to column 33)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 100, column 16 to line 101, column 115)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 99, column 27 to line 102, column 13)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 99, column 12 to line 102, column 13)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 103, column 12 to column 46)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 97, column 22 to line 104, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 97, column 8 to line 104, column 9)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 96, column 19 to line 105, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 96, column 4 to line 105, column 5)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 3, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 4, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 6, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 6, column 13 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 6, column 4 to column 18)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 8, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 11, column 11 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 11, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 12, column 11 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 12, column 15 to column 18)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 12, column 4 to column 28)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 15, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 15, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 16, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 16, column 13 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 16, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 19, column 4 to column 26)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 20, column 4 to column 26)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 23, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 24, column 4 to column 25)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 27, column 4 to column 27)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 28, column 4 to column 27)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 31, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 32, column 4 to column 23)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 38, column 4 to column 19)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 40, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 41, column 11 to column 16)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 41, column 4 to column 24)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 43, column 11 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 43, column 15 to column 18)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 43, column 4 to column 22)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 48, column 11 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 48, column 15 to column 16)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 49, column 29 to column 30)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 49, column 31 to column 32)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 50, column 11 to column 12)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 50, column 13 to column 14)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 55, column 28 to column 31)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 61, column 12 to column 13)",
 " (in '/home/riccardo/bayesian-project/dirichlet.stan', line 64, column 29 to column 32)"};




class dirichlet_model final : public model_base_crtp<dirichlet_model> {

 private:
  int I;
  int T;
  Eigen::Matrix<double, -1, -1> y_data__;
  int p;
  Eigen::Matrix<double, -1, 1> mu_0_data__;
  Eigen::Matrix<double, -1, -1> Sigma_0_data__;
  Eigen::Matrix<double, -1, 1> mu_w_1_data__;
  Eigen::Matrix<double, -1, -1> inv_Q_w_data__;
  double a_alpha;
  double b_alpha;
  double a_tau2;
  double b_tau2;
  double a_sigma2;
  double b_sigma2;
  double a_xi;
  double b_xi;
  int H;
  int ngrid;
  Eigen::Matrix<double, -1, 1> xgrid_data__;
  Eigen::Matrix<double, -1, -1> X_data__;
  int betas_1dim__;
  int vs_1dim__;
  int cumprod_one_mv_1dim__; 
  Eigen::Map<Eigen::Matrix<double, -1, -1>> y{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mu_0{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> Sigma_0{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mu_w_1{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> inv_Q_w{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> xgrid{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> X{nullptr, 0, 0};
 
 public:
  ~dirichlet_model() { }
  
  inline std::string model_name() const final { return "dirichlet_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.30.1", "stancflags = "};
  }
  
  
  dirichlet_model(stan::io::var_context& context__,
                  unsigned int random_seed__ = 0,
                  std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "dirichlet_model_namespace::dirichlet_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 44;
      context__.validate_dims("data initialization","I","int",
           std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      
      
      current_statement__ = 44;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 44;
      stan::math::check_greater_or_equal(function__, "I", I, 1);
      current_statement__ = 45;
      context__.validate_dims("data initialization","T","int",
           std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      
      
      current_statement__ = 45;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 45;
      stan::math::check_greater_or_equal(function__, "T", T, 1);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("y", "I", I);
      current_statement__ = 47;
      stan::math::validate_non_negative_index("y", "T", T);
      current_statement__ = 48;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(T)});
      y_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant(I, T,
          std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double, -1, -1>>(y_data__.data(), I, T);
        
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 48;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 48;
        pos__ = 1;
        current_statement__ = 48;
        for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
          current_statement__ = 48;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 48;
            stan::model::assign(y, y_flat__[(pos__ - 1)],
              "assigning variable y", stan::model::index_uni(sym2__),
                                        stan::model::index_uni(sym1__));
            current_statement__ = 48;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 49;
      context__.validate_dims("data initialization","p","int",
           std::vector<size_t>{});
      p = std::numeric_limits<int>::min();
      
      
      current_statement__ = 49;
      p = context__.vals_i("p")[(1 - 1)];
      current_statement__ = 49;
      stan::math::check_greater_or_equal(function__, "p", p, 1);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("mu_0", "p + 1", (p + 1));
      current_statement__ = 51;
      context__.validate_dims("data initialization","mu_0","double",
           std::vector<size_t>{static_cast<size_t>((p + 1))});
      mu_0_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant((p + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&mu_0) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mu_0_data__.data(), 
        (p + 1));
      
      {
        std::vector<local_scalar_t__> mu_0_flat__;
        current_statement__ = 51;
        mu_0_flat__ = context__.vals_r("mu_0");
        current_statement__ = 51;
        pos__ = 1;
        current_statement__ = 51;
        for (int sym1__ = 1; sym1__ <= (p + 1); ++sym1__) {
          current_statement__ = 51;
          stan::model::assign(mu_0, mu_0_flat__[(pos__ - 1)],
            "assigning variable mu_0", stan::model::index_uni(sym1__));
          current_statement__ = 51;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 52;
      stan::math::validate_non_negative_index("Sigma_0", "p + 1", (p + 1));
      current_statement__ = 53;
      stan::math::validate_non_negative_index("Sigma_0", "p + 1", (p + 1));
      current_statement__ = 54;
      context__.validate_dims("data initialization","Sigma_0","double",
           std::vector<size_t>{static_cast<size_t>((p + 1)),
            static_cast<size_t>((p + 1))});
      Sigma_0_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant((p + 1), (p + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&Sigma_0) Eigen::Map<Eigen::Matrix<double, -1, -1>>(Sigma_0_data__.data(), 
        (p + 1), (p + 1));
      
      {
        std::vector<local_scalar_t__> Sigma_0_flat__;
        current_statement__ = 54;
        Sigma_0_flat__ = context__.vals_r("Sigma_0");
        current_statement__ = 54;
        pos__ = 1;
        current_statement__ = 54;
        for (int sym1__ = 1; sym1__ <= (p + 1); ++sym1__) {
          current_statement__ = 54;
          for (int sym2__ = 1; sym2__ <= (p + 1); ++sym2__) {
            current_statement__ = 54;
            stan::model::assign(Sigma_0, Sigma_0_flat__[(pos__ - 1)],
              "assigning variable Sigma_0", stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
            current_statement__ = 54;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 55;
      stan::math::validate_non_negative_index("mu_w_1", "I", I);
      current_statement__ = 56;
      context__.validate_dims("data initialization","mu_w_1","double",
           std::vector<size_t>{static_cast<size_t>(I)});
      mu_w_1_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(I,
          std::numeric_limits<double>::quiet_NaN());
      new (&mu_w_1) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mu_w_1_data__.data(), I);
        
      
      {
        std::vector<local_scalar_t__> mu_w_1_flat__;
        current_statement__ = 56;
        mu_w_1_flat__ = context__.vals_r("mu_w_1");
        current_statement__ = 56;
        pos__ = 1;
        current_statement__ = 56;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 56;
          stan::model::assign(mu_w_1, mu_w_1_flat__[(pos__ - 1)],
            "assigning variable mu_w_1", stan::model::index_uni(sym1__));
          current_statement__ = 56;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 57;
      stan::math::validate_non_negative_index("inv_Q_w", "I", I);
      current_statement__ = 58;
      stan::math::validate_non_negative_index("inv_Q_w", "I", I);
      current_statement__ = 59;
      context__.validate_dims("data initialization","inv_Q_w","double",
           std::vector<size_t>{static_cast<size_t>(I),
            static_cast<size_t>(I)});
      inv_Q_w_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant(I, I,
          std::numeric_limits<double>::quiet_NaN());
      new (&inv_Q_w) Eigen::Map<Eigen::Matrix<double, -1, -1>>(inv_Q_w_data__.data(), I, I);
        
      
      {
        std::vector<local_scalar_t__> inv_Q_w_flat__;
        current_statement__ = 59;
        inv_Q_w_flat__ = context__.vals_r("inv_Q_w");
        current_statement__ = 59;
        pos__ = 1;
        current_statement__ = 59;
        for (int sym1__ = 1; sym1__ <= I; ++sym1__) {
          current_statement__ = 59;
          for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
            current_statement__ = 59;
            stan::model::assign(inv_Q_w, inv_Q_w_flat__[(pos__ - 1)],
              "assigning variable inv_Q_w", stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
            current_statement__ = 59;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 60;
      context__.validate_dims("data initialization","a_alpha","double",
           std::vector<size_t>{});
      a_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 60;
      a_alpha = context__.vals_r("a_alpha")[(1 - 1)];
      current_statement__ = 60;
      stan::math::check_greater_or_equal(function__, "a_alpha", a_alpha, 0);
      current_statement__ = 61;
      context__.validate_dims("data initialization","b_alpha","double",
           std::vector<size_t>{});
      b_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 61;
      b_alpha = context__.vals_r("b_alpha")[(1 - 1)];
      current_statement__ = 61;
      stan::math::check_greater_or_equal(function__, "b_alpha", b_alpha, 0);
      current_statement__ = 62;
      context__.validate_dims("data initialization","a_tau2","double",
           std::vector<size_t>{});
      a_tau2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 62;
      a_tau2 = context__.vals_r("a_tau2")[(1 - 1)];
      current_statement__ = 62;
      stan::math::check_greater_or_equal(function__, "a_tau2", a_tau2, 0);
      current_statement__ = 63;
      context__.validate_dims("data initialization","b_tau2","double",
           std::vector<size_t>{});
      b_tau2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 63;
      b_tau2 = context__.vals_r("b_tau2")[(1 - 1)];
      current_statement__ = 63;
      stan::math::check_greater_or_equal(function__, "b_tau2", b_tau2, 0);
      current_statement__ = 64;
      context__.validate_dims("data initialization","a_sigma2","double",
           std::vector<size_t>{});
      a_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 64;
      a_sigma2 = context__.vals_r("a_sigma2")[(1 - 1)];
      current_statement__ = 64;
      stan::math::check_greater_or_equal(function__, "a_sigma2", a_sigma2, 0);
      current_statement__ = 65;
      context__.validate_dims("data initialization","b_sigma2","double",
           std::vector<size_t>{});
      b_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 65;
      b_sigma2 = context__.vals_r("b_sigma2")[(1 - 1)];
      current_statement__ = 65;
      stan::math::check_greater_or_equal(function__, "b_sigma2", b_sigma2, 0);
      current_statement__ = 66;
      context__.validate_dims("data initialization","a_xi","double",
           std::vector<size_t>{});
      a_xi = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 66;
      a_xi = context__.vals_r("a_xi")[(1 - 1)];
      current_statement__ = 66;
      stan::math::check_greater_or_equal(function__, "a_xi", a_xi, 0);
      current_statement__ = 67;
      context__.validate_dims("data initialization","b_xi","double",
           std::vector<size_t>{});
      b_xi = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 67;
      b_xi = context__.vals_r("b_xi")[(1 - 1)];
      current_statement__ = 67;
      stan::math::check_greater_or_equal(function__, "b_xi", b_xi, 0);
      current_statement__ = 68;
      context__.validate_dims("data initialization","H","int",
           std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      
      
      current_statement__ = 68;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 68;
      stan::math::check_greater_or_equal(function__, "H", H, 1);
      current_statement__ = 69;
      context__.validate_dims("data initialization","ngrid","int",
           std::vector<size_t>{});
      ngrid = std::numeric_limits<int>::min();
      
      
      current_statement__ = 69;
      ngrid = context__.vals_i("ngrid")[(1 - 1)];
      current_statement__ = 69;
      stan::math::check_greater_or_equal(function__, "ngrid", ngrid, 1);
      current_statement__ = 70;
      stan::math::validate_non_negative_index("xgrid", "ngrid", ngrid);
      current_statement__ = 71;
      context__.validate_dims("data initialization","xgrid","double",
           std::vector<size_t>{static_cast<size_t>(ngrid)});
      xgrid_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(ngrid,
          std::numeric_limits<double>::quiet_NaN());
      new (&xgrid) Eigen::Map<Eigen::Matrix<double, -1, 1>>(xgrid_data__.data(), ngrid);
        
      
      {
        std::vector<local_scalar_t__> xgrid_flat__;
        current_statement__ = 71;
        xgrid_flat__ = context__.vals_r("xgrid");
        current_statement__ = 71;
        pos__ = 1;
        current_statement__ = 71;
        for (int sym1__ = 1; sym1__ <= ngrid; ++sym1__) {
          current_statement__ = 71;
          stan::model::assign(xgrid, xgrid_flat__[(pos__ - 1)],
            "assigning variable xgrid", stan::model::index_uni(sym1__));
          current_statement__ = 71;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 72;
      stan::math::validate_non_negative_index("X", "I * T", (I * T));
      current_statement__ = 73;
      stan::math::validate_non_negative_index("X", "p + 1", (p + 1));
      current_statement__ = 74;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>((I * T)),
            static_cast<size_t>((p + 1))});
      X_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant((I * T), (p + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double, -1, -1>>(X_data__.data(), 
        (I * T), (p + 1));
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 74;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 74;
        pos__ = 1;
        current_statement__ = 74;
        for (int sym1__ = 1; sym1__ <= (p + 1); ++sym1__) {
          current_statement__ = 74;
          for (int sym2__ = 1; sym2__ <= (I * T); ++sym2__) {
            current_statement__ = 74;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
                                        stan::model::index_uni(sym1__));
            current_statement__ = 74;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 75;
      betas_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 75;
      betas_1dim__ = (p + 1);
      current_statement__ = 75;
      stan::math::validate_non_negative_index("betas", "p + 1", betas_1dim__);
      current_statement__ = 76;
      stan::math::validate_non_negative_index("betas", "H", H);
      current_statement__ = 77;
      stan::math::validate_non_negative_index("xis", "I", I);
      current_statement__ = 78;
      stan::math::validate_non_negative_index("xis", "H", H);
      current_statement__ = 79;
      stan::math::validate_non_negative_index("ws", "I", I);
      current_statement__ = 80;
      stan::math::validate_non_negative_index("ws", "T", T);
      current_statement__ = 81;
      vs_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 81;
      vs_1dim__ = (H - 1);
      current_statement__ = 81;
      stan::math::validate_non_negative_index("vs", "H - 1", vs_1dim__);
      current_statement__ = 82;
      stan::math::validate_non_negative_index("omegas", "H", H);
      current_statement__ = 83;
      cumprod_one_mv_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 83;
      cumprod_one_mv_1dim__ = (H - 1);
      current_statement__ = 83;
      stan::math::validate_non_negative_index("cumprod_one_mv", "H - 1",
                                              cumprod_one_mv_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + (betas_1dim__ * H) + (I * H) + (I * T) + 1 + 
      1 + 1 + vs_1dim__;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "dirichlet_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, -1> betas =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(betas_1dim__, H,
           DUMMY_VAR__);
      current_statement__ = 2;
      betas = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(
                betas_1dim__, H);
      Eigen::Matrix<local_scalar_t__, -1, -1> xis =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(I, H, DUMMY_VAR__);
      current_statement__ = 3;
      xis = in__.template read_constrain_lub<
              Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(-1, 1,
              lp__, I, H);
      Eigen::Matrix<local_scalar_t__, -1, -1> ws =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(I, T, DUMMY_VAR__);
      current_statement__ = 4;
      ws = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(I, T);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 5;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      local_scalar_t__ tau2 = DUMMY_VAR__;
      current_statement__ = 6;
      tau2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      local_scalar_t__ rho = DUMMY_VAR__;
      current_statement__ = 7;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<local_scalar_t__, -1, 1> vs =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(vs_1dim__,
           DUMMY_VAR__);
      current_statement__ = 8;
      vs = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1, lp__,
             vs_1dim__);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 9;
      sigma = stan::math::sqrt(sigma2);
      Eigen::Matrix<local_scalar_t__, -1, 1> omegas =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(H, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> cumprod_one_mv =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
           cumprod_one_mv_1dim__, DUMMY_VAR__);
      current_statement__ = 12;
      stan::model::assign(cumprod_one_mv,
        stan::math::exp(stan::math::cumulative_sum(stan::math::log1m(vs))),
        "assigning variable cumprod_one_mv");
      current_statement__ = 13;
      stan::model::assign(omegas,
        stan::model::rvalue(vs, "vs", stan::model::index_uni(1)),
        "assigning variable omegas", stan::model::index_uni(1));
      current_statement__ = 14;
      stan::model::assign(omegas,
        stan::math::elt_multiply(
          stan::model::rvalue(vs, "vs",
            stan::model::index_min_max(2, (H - 1))),
          stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
            stan::model::index_min_max(1, (H - 2)))),
        "assigning variable omegas", stan::model::index_min_max(2, (H - 1)));
      current_statement__ = 15;
      stan::model::assign(omegas,
        stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
          stan::model::index_uni((H - 1))),
        "assigning variable omegas", stan::model::index_uni(H));
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "sigma", sigma, 0);
      current_statement__ = 10;
      stan::math::check_simplex(function__, "omegas", omegas);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "cumprod_one_mv",
                                            cumprod_one_mv, 0);
      current_statement__ = 11;
      stan::math::check_less_or_equal(function__, "cumprod_one_mv",
                                         cumprod_one_mv, 1);
      {
        current_statement__ = 16;
        lp_accum__.add(
          stan::math::gamma_lpdf<propto__>(alpha, a_alpha, b_alpha));
        current_statement__ = 17;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(vs, 1, alpha));
        current_statement__ = 18;
        lp_accum__.add(
          stan::math::inv_gamma_lpdf<propto__>(sigma2, a_sigma2, b_sigma2));
        current_statement__ = 19;
        lp_accum__.add(
          stan::math::inv_gamma_lpdf<propto__>(tau2, a_tau2, b_tau2));
        current_statement__ = 22;
        for (int h = 1; h <= H; ++h) {
          current_statement__ = 20;
          lp_accum__.add(
            stan::math::multi_normal_lpdf<propto__>(
              stan::model::rvalue(betas, "betas",
                stan::model::index_min_max(1, (p + 1)),
                  stan::model::index_uni(h)), mu_0, Sigma_0));
        }
        current_statement__ = 27;
        for (int h = 1; h <= H; ++h) {
          current_statement__ = 25;
          for (int i = 1; i <= I; ++i) {
            current_statement__ = 23;
            lp_accum__.add(
              stan::math::beta_lpdf<propto__>(
                stan::model::rvalue(xis, "xis",
                  stan::model::index_uni(i), stan::model::index_uni(h)),
                a_xi, b_xi));
          }
        }
        current_statement__ = 28;
        lp_accum__.add(
          stan::math::multi_normal_lpdf<propto__>(
            stan::model::rvalue(ws, "ws",
              stan::model::index_min_max(1, I), stan::model::index_uni(1)),
            mu_w_1, stan::math::multiply(tau2, inv_Q_w)));
        current_statement__ = 33;
        for (int t = 2; t <= T; ++t) {
          current_statement__ = 31;
          for (int h = 1; h <= H; ++h) {
            current_statement__ = 29;
            lp_accum__.add(
              stan::math::multi_normal_lpdf<propto__>(
                stan::model::rvalue(ws, "ws",
                  stan::model::index_min_max(1, I), stan::model::index_uni(t)),
                stan::math::multiply(
                  stan::math::diag_matrix(
                    stan::model::rvalue(xis, "xis",
                      stan::model::index_min_max(1, I),
                        stan::model::index_uni(h))),
                  stan::model::rvalue(ws, "ws",
                    stan::model::index_min_max(1, I),
                      stan::model::index_uni((t - 1)))),
                stan::math::multiply(tau2, inv_Q_w)));
          }
        }
        current_statement__ = 43;
        for (int t = 1; t <= T; ++t) {
          current_statement__ = 41;
          for (int i = 1; i <= I; ++i) {
            current_statement__ = 34;
            stan::math::validate_non_negative_index("log_probas", "H", H);
            Eigen::Matrix<local_scalar_t__, -1, 1> log_probas =
               Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(H,
                 DUMMY_VAR__);
            current_statement__ = 38;
            for (int h = 1; h <= H; ++h) {
              current_statement__ = 36;
              stan::model::assign(log_probas,
                (stan::math::log(
                   stan::model::rvalue(omegas, "omegas",
                     stan::model::index_uni(h))) +
                  stan::math::normal_lpdf<false>(
                    stan::model::rvalue(y, "y",
                      stan::model::index_uni(i), stan::model::index_uni(t)),
                    (stan::math::dot_product(
                       stan::model::rvalue(X, "X",
                         stan::model::index_uni(i),
                           stan::model::index_min_max(1, (p + 1))),
                       stan::model::rvalue(betas, "betas",
                         stan::model::index_min_max(1, (p + 1)),
                           stan::model::index_uni(h))) +
                      stan::model::rvalue(ws, "ws",
                        stan::model::index_uni(i), stan::model::index_uni(t))),
                    sigma)),
                "assigning variable log_probas", stan::model::index_uni(h));
            }
            current_statement__ = 39;
            lp_accum__.add(stan::math::log_sum_exp(log_probas));
          }
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "dirichlet_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      Eigen::Matrix<double, -1, -1> betas =
         Eigen::Matrix<double, -1, -1>::Constant(betas_1dim__, H,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 2;
      betas = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(
                betas_1dim__, H);
      Eigen::Matrix<double, -1, -1> xis =
         Eigen::Matrix<double, -1, -1>::Constant(I, H,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      xis = in__.template read_constrain_lub<
              Eigen::Matrix<local_scalar_t__, -1, -1>, jacobian__>(-1, 1,
              lp__, I, H);
      Eigen::Matrix<double, -1, -1> ws =
         Eigen::Matrix<double, -1, -1>::Constant(I, T,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      ws = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(I, T);
      double sigma2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 5;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      double tau2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 6;
      tau2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
               lp__);
      double rho = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 7;
      rho = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(0,
              lp__);
      Eigen::Matrix<double, -1, 1> vs =
         Eigen::Matrix<double, -1, 1>::Constant(vs_1dim__,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 8;
      vs = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1, lp__,
             vs_1dim__);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      Eigen::Matrix<double, -1, 1> omegas =
         Eigen::Matrix<double, -1, 1>::Constant(H,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> cumprod_one_mv =
         Eigen::Matrix<double, -1, 1>::Constant(cumprod_one_mv_1dim__,
           std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(betas);
      out__.write(xis);
      out__.write(ws);
      out__.write(sigma2);
      out__.write(tau2);
      out__.write(rho);
      out__.write(vs);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 9;
      sigma = stan::math::sqrt(sigma2);
      current_statement__ = 12;
      stan::model::assign(cumprod_one_mv,
        stan::math::exp(stan::math::cumulative_sum(stan::math::log1m(vs))),
        "assigning variable cumprod_one_mv");
      current_statement__ = 13;
      stan::model::assign(omegas,
        stan::model::rvalue(vs, "vs", stan::model::index_uni(1)),
        "assigning variable omegas", stan::model::index_uni(1));
      current_statement__ = 14;
      stan::model::assign(omegas,
        stan::math::elt_multiply(
          stan::model::rvalue(vs, "vs",
            stan::model::index_min_max(2, (H - 1))),
          stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
            stan::model::index_min_max(1, (H - 2)))),
        "assigning variable omegas", stan::model::index_min_max(2, (H - 1)));
      current_statement__ = 15;
      stan::model::assign(omegas,
        stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
          stan::model::index_uni((H - 1))),
        "assigning variable omegas", stan::model::index_uni(H));
      current_statement__ = 9;
      stan::math::check_greater_or_equal(function__, "sigma", sigma, 0);
      current_statement__ = 10;
      stan::math::check_simplex(function__, "omegas", omegas);
      current_statement__ = 11;
      stan::math::check_greater_or_equal(function__, "cumprod_one_mv",
                                            cumprod_one_mv, 0);
      current_statement__ = 11;
      stan::math::check_less_or_equal(function__, "cumprod_one_mv",
                                         cumprod_one_mv, 1);
      if (emit_transformed_parameters__) {
        out__.write(sigma);
        out__.write(omegas);
        out__.write(cumprod_one_mv);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      Eigen::Matrix<local_scalar_t__, -1, -1> betas =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(betas_1dim__, H,
           DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          stan::model::assign(betas, in__.read<local_scalar_t__>(),
            "assigning variable betas", stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
        }
      }
      out__.write(betas);
      Eigen::Matrix<local_scalar_t__, -1, -1> xis =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(I, H, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          stan::model::assign(xis, in__.read<local_scalar_t__>(),
            "assigning variable xis", stan::model::index_uni(sym2__),
                                        stan::model::index_uni(sym1__));
        }
      }
      out__.write_free_lub(-1, 1, xis);
      Eigen::Matrix<local_scalar_t__, -1, -1> ws =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(I, T, DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          stan::model::assign(ws, in__.read<local_scalar_t__>(),
            "assigning variable ws", stan::model::index_uni(sym2__),
                                       stan::model::index_uni(sym1__));
        }
      }
      out__.write(ws);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      sigma2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma2);
      local_scalar_t__ tau2 = DUMMY_VAR__;
      tau2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, tau2);
      local_scalar_t__ rho = DUMMY_VAR__;
      rho = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, rho);
      Eigen::Matrix<local_scalar_t__, -1, 1> vs =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(vs_1dim__,
           DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
        stan::model::assign(vs, in__.read<local_scalar_t__>(),
          "assigning variable vs", stan::model::index_uni(sym1__));
      }
      out__.write_free_lub(0, 1, vs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "betas", "xis", "ws",
      "sigma2", "tau2", "rho", "vs", "sigma", "omegas", "cumprod_one_mv"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(betas_1dim__),
                          static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(I), static_cast<size_t>(T)},
      std::vector<size_t>{}, std::vector<size_t>{}, std::vector<size_t>{
      }, std::vector<size_t>{static_cast<size_t>(vs_1dim__)},
      std::vector<size_t>{}, std::vector<size_t>{static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(cumprod_one_mv_1dim__)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "xis" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "ws" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "tau2");
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "vs" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma");
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "omegas" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= cumprod_one_mv_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cumprod_one_mv" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "xis" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= T; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= I; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "ws" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    param_names__.emplace_back(std::string() + "sigma2");
    param_names__.emplace_back(std::string() + "tau2");
    param_names__.emplace_back(std::string() + "rho");
    for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "vs" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      param_names__.emplace_back(std::string() + "sigma");
      for (int sym1__ = 1; sym1__ <= (H - 1); ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "omegas" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= cumprod_one_mv_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cumprod_one_mv" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(betas_1dim__) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"xis\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(vs_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"omegas\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(H) + "},\"block\":\"transformed_parameters\"},{\"name\":\"cumprod_one_mv\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(cumprod_one_mv_1dim__) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(betas_1dim__) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"xis\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"ws\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(I) + ",\"cols\":" + std::to_string(T) + "},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"tau2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"rho\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"vs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(vs_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"transformed_parameters\"},{\"name\":\"omegas\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((H - 1)) + "},\"block\":\"transformed_parameters\"},{\"name\":\"cumprod_one_mv\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(cumprod_one_mv_1dim__) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((1 + (betas_1dim__ * H)) + (I * H)) + (I * T)) + 1) + 1) + 1) +
    vs_1dim__);
      const size_t num_transformed = emit_transformed_parameters * 
  ((1 + H) + cumprod_one_mv_1dim__);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((((((1 + (betas_1dim__ * H)) + (I * H)) + (I * T)) + 1) + 1) + 1) +
    vs_1dim__);
      const size_t num_transformed = emit_transformed_parameters * 
  ((1 + H) + cumprod_one_mv_1dim__);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 8> names__{"alpha", "betas", "xis",
      "ws", "sigma2", "tau2", "rho", "vs"};
      const std::array<Eigen::Index, 8> constrain_param_sizes__{1,
       (betas_1dim__ * H), (I * H), (I * T), 1, 1, 1, vs_1dim__};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}
using stan_model = dirichlet_model_namespace::dirichlet_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return dirichlet_model_namespace::profiles__;
}

#endif


