
// Code generated by stanc v2.31.0
#include <stan/model/model_header.hpp>
namespace SimpleModel_NoRandomEffect_model_namespace {

using stan::model::model_base_crtp;
using namespace stan::math;


stan::math::profile_map profiles__;
static constexpr std::array<const char*, 54> locations_array__ = 
{" (found before start of program)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 42, column 4 to column 24)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 43, column 4 to column 25)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 44, column 4 to column 24)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 45, column 4 to column 36)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 49, column 4 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 51, column 4 to column 31)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 52, column 4 to column 52)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 54, column 4 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 55, column 4 to column 61)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 56, column 4 to column 36)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 60, column 4 to column 35)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 61, column 4 to column 42)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 62, column 4 to column 23)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 65, column 8 to column 53)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 64, column 4 to line 65, column 53)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 69, column 15 to column 16)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 69, column 8 to column 28)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 72, column 12 to column 136)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 71, column 8 to line 72, column 136)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 74, column 8 to column 41)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 67, column 19 to line 75, column 5)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 67, column 4 to line 75, column 5)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 10, column 4 to column 10)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 11, column 4 to column 10)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 12, column 4 to column 10)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 13, column 4 to column 10)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 15, column 11 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 15, column 4 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 16, column 11 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 16, column 15 to column 18)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 16, column 4 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 20, column 4 to column 27)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 21, column 4 to column 27)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 24, column 11 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 24, column 4 to column 21)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 25, column 11 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 25, column 15 to column 18)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 25, column 4 to column 28)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 28, column 4 to column 26)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 29, column 4 to column 26)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 34, column 11 to column 12)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 34, column 4 to column 21)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 36, column 8 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 35, column 4 to line 36, column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 38, column 11 to column 12)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 38, column 13 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 38, column 4 to column 22)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 39, column 4 to column 32)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 44, column 11 to column 14)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 44, column 15 to column 16)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 45, column 28 to column 31)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 49, column 12 to column 13)",
 " (in '/home/anna-ubuntu/bayesian-project/SimpleModel_NoRandomEffect.stan', line 51, column 11 to column 14)"};




class SimpleModel_NoRandomEffect_model final : public model_base_crtp<SimpleModel_NoRandomEffect_model> {

 private:
  int I;
  int T;
  int P;
  int H;
  Eigen::Matrix<double, -1, 1> y_data__;
  Eigen::Matrix<double, -1, -1> X_data__;
  double a_sigma2;
  double b_sigma2;
  Eigen::Matrix<double, -1, 1> mu_0_data__;
  Eigen::Matrix<double, -1, -1> Sigma_0_data__;
  double a_alpha;
  double b_alpha;
  Eigen::Matrix<double, -1, 1> ones_T_data__;
  Eigen::Matrix<double, -1, -1> eye_T_data__;
  int betas_1dim__;
  int vs_1dim__;
  int cumprod_one_mv_1dim__; 
  Eigen::Map<Eigen::Matrix<double, -1, 1>> y{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> X{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> mu_0{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> Sigma_0{nullptr, 0, 0};
  Eigen::Map<Eigen::Matrix<double, -1, 1>> ones_T{nullptr, 0};
  Eigen::Map<Eigen::Matrix<double, -1, -1>> eye_T{nullptr, 0, 0};
 
 public:
  ~SimpleModel_NoRandomEffect_model() { }
  
  inline std::string model_name() const final { return "SimpleModel_NoRandomEffect_model"; }

  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.31.0", "stancflags = "};
  }
  
  
  SimpleModel_NoRandomEffect_model(stan::io::var_context& context__,
                                   unsigned int random_seed__ = 0,
                                   std::ostream* pstream__ = nullptr) : model_base_crtp(0) {
    int current_statement__ = 0;
    using local_scalar_t__ = double ;
    boost::ecuyer1988 base_rng__ = 
        stan::services::util::create_rng(random_seed__, 0);
    (void) base_rng__;  // suppress unused var warning
    static constexpr const char* function__ = "SimpleModel_NoRandomEffect_model_namespace::SimpleModel_NoRandomEffect_model";
    (void) function__;  // suppress unused var warning
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 23;
      context__.validate_dims("data initialization","I","int",
           std::vector<size_t>{});
      I = std::numeric_limits<int>::min();
      
      
      current_statement__ = 23;
      I = context__.vals_i("I")[(1 - 1)];
      current_statement__ = 24;
      context__.validate_dims("data initialization","T","int",
           std::vector<size_t>{});
      T = std::numeric_limits<int>::min();
      
      
      current_statement__ = 24;
      T = context__.vals_i("T")[(1 - 1)];
      current_statement__ = 25;
      context__.validate_dims("data initialization","P","int",
           std::vector<size_t>{});
      P = std::numeric_limits<int>::min();
      
      
      current_statement__ = 25;
      P = context__.vals_i("P")[(1 - 1)];
      current_statement__ = 26;
      context__.validate_dims("data initialization","H","int",
           std::vector<size_t>{});
      H = std::numeric_limits<int>::min();
      
      
      current_statement__ = 26;
      H = context__.vals_i("H")[(1 - 1)];
      current_statement__ = 27;
      stan::math::validate_non_negative_index("y", "I * T", (I * T));
      current_statement__ = 28;
      context__.validate_dims("data initialization","y","double",
           std::vector<size_t>{static_cast<size_t>((I * T))});
      y_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant((I * T),
          std::numeric_limits<double>::quiet_NaN());
      new (&y) Eigen::Map<Eigen::Matrix<double, -1, 1>>(y_data__.data(), 
        (I * T));
      
      {
        std::vector<local_scalar_t__> y_flat__;
        current_statement__ = 28;
        y_flat__ = context__.vals_r("y");
        current_statement__ = 28;
        pos__ = 1;
        current_statement__ = 28;
        for (int sym1__ = 1; sym1__ <= (I * T); ++sym1__) {
          current_statement__ = 28;
          stan::model::assign(y, y_flat__[(pos__ - 1)],
            "assigning variable y", stan::model::index_uni(sym1__));
          current_statement__ = 28;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 29;
      stan::math::validate_non_negative_index("X", "I * T", (I * T));
      current_statement__ = 30;
      stan::math::validate_non_negative_index("X", "P + 1", (P + 1));
      current_statement__ = 31;
      context__.validate_dims("data initialization","X","double",
           std::vector<size_t>{static_cast<size_t>((I * T)),
            static_cast<size_t>((P + 1))});
      X_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant((I * T), (P + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&X) Eigen::Map<Eigen::Matrix<double, -1, -1>>(X_data__.data(), 
        (I * T), (P + 1));
      
      {
        std::vector<local_scalar_t__> X_flat__;
        current_statement__ = 31;
        X_flat__ = context__.vals_r("X");
        current_statement__ = 31;
        pos__ = 1;
        current_statement__ = 31;
        for (int sym1__ = 1; sym1__ <= (P + 1); ++sym1__) {
          current_statement__ = 31;
          for (int sym2__ = 1; sym2__ <= (I * T); ++sym2__) {
            current_statement__ = 31;
            stan::model::assign(X, X_flat__[(pos__ - 1)],
              "assigning variable X", stan::model::index_uni(sym2__),
                                        stan::model::index_uni(sym1__));
            current_statement__ = 31;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 32;
      context__.validate_dims("data initialization","a_sigma2","double",
           std::vector<size_t>{});
      a_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 32;
      a_sigma2 = context__.vals_r("a_sigma2")[(1 - 1)];
      current_statement__ = 32;
      stan::math::check_greater_or_equal(function__, "a_sigma2", a_sigma2, 0);
      current_statement__ = 33;
      context__.validate_dims("data initialization","b_sigma2","double",
           std::vector<size_t>{});
      b_sigma2 = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 33;
      b_sigma2 = context__.vals_r("b_sigma2")[(1 - 1)];
      current_statement__ = 33;
      stan::math::check_greater_or_equal(function__, "b_sigma2", b_sigma2, 0);
      current_statement__ = 34;
      stan::math::validate_non_negative_index("mu_0", "P + 1", (P + 1));
      current_statement__ = 35;
      context__.validate_dims("data initialization","mu_0","double",
           std::vector<size_t>{static_cast<size_t>((P + 1))});
      mu_0_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant((P + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&mu_0) Eigen::Map<Eigen::Matrix<double, -1, 1>>(mu_0_data__.data(), 
        (P + 1));
      
      {
        std::vector<local_scalar_t__> mu_0_flat__;
        current_statement__ = 35;
        mu_0_flat__ = context__.vals_r("mu_0");
        current_statement__ = 35;
        pos__ = 1;
        current_statement__ = 35;
        for (int sym1__ = 1; sym1__ <= (P + 1); ++sym1__) {
          current_statement__ = 35;
          stan::model::assign(mu_0, mu_0_flat__[(pos__ - 1)],
            "assigning variable mu_0", stan::model::index_uni(sym1__));
          current_statement__ = 35;
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 36;
      stan::math::validate_non_negative_index("Sigma_0", "P + 1", (P + 1));
      current_statement__ = 37;
      stan::math::validate_non_negative_index("Sigma_0", "P + 1", (P + 1));
      current_statement__ = 38;
      context__.validate_dims("data initialization","Sigma_0","double",
           std::vector<size_t>{static_cast<size_t>((P + 1)),
            static_cast<size_t>((P + 1))});
      Sigma_0_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant((P + 1), (P + 1),
          std::numeric_limits<double>::quiet_NaN());
      new (&Sigma_0) Eigen::Map<Eigen::Matrix<double, -1, -1>>(Sigma_0_data__.data(), 
        (P + 1), (P + 1));
      
      {
        std::vector<local_scalar_t__> Sigma_0_flat__;
        current_statement__ = 38;
        Sigma_0_flat__ = context__.vals_r("Sigma_0");
        current_statement__ = 38;
        pos__ = 1;
        current_statement__ = 38;
        for (int sym1__ = 1; sym1__ <= (P + 1); ++sym1__) {
          current_statement__ = 38;
          for (int sym2__ = 1; sym2__ <= (P + 1); ++sym2__) {
            current_statement__ = 38;
            stan::model::assign(Sigma_0, Sigma_0_flat__[(pos__ - 1)],
              "assigning variable Sigma_0", stan::model::index_uni(sym2__),
                                              stan::model::index_uni(sym1__));
            current_statement__ = 38;
            pos__ = (pos__ + 1);
          }
        }
      }
      current_statement__ = 39;
      context__.validate_dims("data initialization","a_alpha","double",
           std::vector<size_t>{});
      a_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 39;
      a_alpha = context__.vals_r("a_alpha")[(1 - 1)];
      current_statement__ = 39;
      stan::math::check_greater_or_equal(function__, "a_alpha", a_alpha, 0);
      current_statement__ = 40;
      context__.validate_dims("data initialization","b_alpha","double",
           std::vector<size_t>{});
      b_alpha = std::numeric_limits<double>::quiet_NaN();
      
      
      current_statement__ = 40;
      b_alpha = context__.vals_r("b_alpha")[(1 - 1)];
      current_statement__ = 40;
      stan::math::check_greater_or_equal(function__, "b_alpha", b_alpha, 0);
      current_statement__ = 41;
      stan::math::validate_non_negative_index("ones_T", "T", T);
      current_statement__ = 42;
      ones_T_data__ = 
        Eigen::Matrix<double, -1, 1>::Constant(T,
          std::numeric_limits<double>::quiet_NaN());
      new (&ones_T) Eigen::Map<Eigen::Matrix<double, -1, 1>>(ones_T_data__.data(), T);
        
      
      current_statement__ = 44;
      for (int t = 1; t <= T; ++t) {
        current_statement__ = 43;
        stan::model::assign(ones_T, 1,
          "assigning variable ones_T", stan::model::index_uni(t));
      }
      current_statement__ = 45;
      stan::math::validate_non_negative_index("eye_T", "T", T);
      current_statement__ = 46;
      stan::math::validate_non_negative_index("eye_T", "T", T);
      current_statement__ = 47;
      eye_T_data__ = 
        Eigen::Matrix<double, -1, -1>::Constant(T, T,
          std::numeric_limits<double>::quiet_NaN());
      new (&eye_T) Eigen::Map<Eigen::Matrix<double, -1, -1>>(eye_T_data__.data(), T, T);
        
      
      current_statement__ = 48;
      stan::model::assign(eye_T, stan::math::diag_matrix(ones_T),
        "assigning variable eye_T");
      current_statement__ = 49;
      betas_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 49;
      betas_1dim__ = (P + 1);
      current_statement__ = 49;
      stan::math::validate_non_negative_index("betas", "P + 1", betas_1dim__);
      current_statement__ = 50;
      stan::math::validate_non_negative_index("betas", "H", H);
      current_statement__ = 51;
      vs_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 51;
      vs_1dim__ = (H - 1);
      current_statement__ = 51;
      stan::math::validate_non_negative_index("vs", "H - 1", vs_1dim__);
      current_statement__ = 52;
      stan::math::validate_non_negative_index("omegas", "H", H);
      current_statement__ = 53;
      cumprod_one_mv_1dim__ = std::numeric_limits<int>::min();
      
      
      current_statement__ = 53;
      cumprod_one_mv_1dim__ = (H - 1);
      current_statement__ = 53;
      stan::math::validate_non_negative_index("cumprod_one_mv", "H - 1",
                                              cumprod_one_mv_1dim__);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = 1 + 1 + (betas_1dim__ * H) + vs_1dim__;
    
  }
  
  template <bool propto__, bool jacobian__ , typename VecR, typename VecI, 
  stan::require_vector_like_t<VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline stan::scalar_type_t<VecR> log_prob_impl(VecR& params_r__,
                                                 VecI& params_i__,
                                                 std::ostream* pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "SimpleModel_NoRandomEffect_model_namespace::log_prob";
    (void) function__;  // suppress unused var warning
    
    try {
      local_scalar_t__ alpha = DUMMY_VAR__;
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      current_statement__ = 2;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<local_scalar_t__, -1, -1> betas =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(betas_1dim__, H,
           DUMMY_VAR__);
      current_statement__ = 3;
      betas = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(
                betas_1dim__, H);
      Eigen::Matrix<local_scalar_t__, -1, 1> vs =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(vs_1dim__,
           DUMMY_VAR__);
      current_statement__ = 4;
      vs = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1, lp__,
             vs_1dim__);
      Eigen::Matrix<local_scalar_t__, -1, 1> omegas =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(H, DUMMY_VAR__);
      Eigen::Matrix<local_scalar_t__, -1, 1> cumprod_one_mv =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(
           cumprod_one_mv_1dim__, DUMMY_VAR__);
      current_statement__ = 7;
      stan::model::assign(cumprod_one_mv,
        stan::math::exp(stan::math::cumulative_sum(stan::math::log1m(vs))),
        "assigning variable cumprod_one_mv");
      current_statement__ = 8;
      stan::model::assign(omegas,
        stan::model::rvalue(vs, "vs", stan::model::index_uni(1)),
        "assigning variable omegas", stan::model::index_uni(1));
      current_statement__ = 9;
      stan::model::assign(omegas,
        stan::math::elt_multiply(
          stan::model::rvalue(vs, "vs",
            stan::model::index_min_max(2, (H - 1))),
          stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
            stan::model::index_min_max(1, (H - 2)))),
        "assigning variable omegas", stan::model::index_min_max(2, (H - 1)));
      current_statement__ = 10;
      stan::model::assign(omegas,
        stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
          stan::model::index_uni((H - 1))),
        "assigning variable omegas", stan::model::index_uni(H));
      current_statement__ = 5;
      stan::math::check_simplex(function__, "omegas", omegas);
      {
        current_statement__ = 11;
        lp_accum__.add(
          stan::math::gamma_lpdf<propto__>(alpha, a_alpha, b_alpha));
        current_statement__ = 12;
        lp_accum__.add(
          stan::math::inv_gamma_lpdf<propto__>(sigma2, a_sigma2, b_sigma2));
        current_statement__ = 13;
        lp_accum__.add(stan::math::beta_lpdf<propto__>(vs, 1, alpha));
        current_statement__ = 15;
        for (int h = 1; h <= H; ++h) {
          current_statement__ = 14;
          lp_accum__.add(
            stan::math::multi_normal_lpdf<propto__>(
              stan::model::rvalue(betas, "betas",
                stan::model::index_min_max(1, (P + 1)),
                  stan::model::index_uni(h)), mu_0, Sigma_0));
        }
        current_statement__ = 22;
        for (int i = 1; i <= I; ++i) {
          current_statement__ = 16;
          stan::math::validate_non_negative_index("log_probs", "H", H);
          Eigen::Matrix<local_scalar_t__, -1, 1> log_probs =
             Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(H, DUMMY_VAR__);
          current_statement__ = 19;
          for (int h = 1; h <= H; ++h) {
            current_statement__ = 18;
            stan::model::assign(log_probs,
              (stan::math::log(
                 stan::model::rvalue(omegas, "omegas",
                   stan::model::index_uni(h))) +
                stan::math::multi_normal_lpdf<false>(
                  stan::model::rvalue(y, "y",
                    stan::model::index_min_max(((T * (i - 1)) + 1), (i * T))),
                  stan::math::multiply(
                    stan::model::rvalue(X, "X",
                      stan::model::index_min_max(((T * (i - 1)) + 1), 
                        (i * T)), stan::model::index_min_max(1, (P + 1))),
                    stan::model::rvalue(betas, "betas",
                      stan::model::index_min_max(1, (P + 1)),
                        stan::model::index_uni(h))),
                  stan::math::multiply(sigma2, eye_T))),
              "assigning variable log_probs", stan::model::index_uni(h));
          }
          current_statement__ = 20;
          lp_accum__.add(stan::math::log_sum_exp(log_probs));
        }
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
    } // log_prob_impl() 
    
  template <typename RNG, typename VecR, typename VecI, typename VecVar, 
  stan::require_vector_like_vt<std::is_floating_point, VecR>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr, 
  stan::require_vector_vt<std::is_floating_point, VecVar>* = nullptr> 
  inline void write_array_impl(RNG& base_rng__, VecR& params_r__,
                               VecI& params_i__, VecVar& vars__,
                               const bool emit_transformed_parameters__ = true,
                               const bool emit_generated_quantities__ = true,
                               std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    (void) propto__;
    double lp__ = 0.0;
    (void) lp__;  // dummy to suppress unused var warning
    int current_statement__ = 0; 
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    constexpr bool jacobian__ = false;
    (void) DUMMY_VAR__;  // suppress unused var warning
    static constexpr const char* function__ = "SimpleModel_NoRandomEffect_model_namespace::write_array";
    (void) function__;  // suppress unused var warning
    
    try {
      double alpha = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 1;
      alpha = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                0, lp__);
      double sigma2 = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma2 = in__.template read_constrain_lb<local_scalar_t__, jacobian__>(
                 0, lp__);
      Eigen::Matrix<double, -1, -1> betas =
         Eigen::Matrix<double, -1, -1>::Constant(betas_1dim__, H,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 3;
      betas = in__.template read<Eigen::Matrix<local_scalar_t__, -1, -1>>(
                betas_1dim__, H);
      Eigen::Matrix<double, -1, 1> vs =
         Eigen::Matrix<double, -1, 1>::Constant(vs_1dim__,
           std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 4;
      vs = in__.template read_constrain_lub<
             Eigen::Matrix<local_scalar_t__, -1, 1>, jacobian__>(0, 1, lp__,
             vs_1dim__);
      Eigen::Matrix<double, -1, 1> omegas =
         Eigen::Matrix<double, -1, 1>::Constant(H,
           std::numeric_limits<double>::quiet_NaN());
      Eigen::Matrix<double, -1, 1> cumprod_one_mv =
         Eigen::Matrix<double, -1, 1>::Constant(cumprod_one_mv_1dim__,
           std::numeric_limits<double>::quiet_NaN());
      out__.write(alpha);
      out__.write(sigma2);
      out__.write(betas);
      out__.write(vs);
      if (stan::math::logical_negation((stan::math::primitive_value(
            emit_transformed_parameters__) || stan::math::primitive_value(
            emit_generated_quantities__)))) {
        return ;
      } 
      current_statement__ = 7;
      stan::model::assign(cumprod_one_mv,
        stan::math::exp(stan::math::cumulative_sum(stan::math::log1m(vs))),
        "assigning variable cumprod_one_mv");
      current_statement__ = 8;
      stan::model::assign(omegas,
        stan::model::rvalue(vs, "vs", stan::model::index_uni(1)),
        "assigning variable omegas", stan::model::index_uni(1));
      current_statement__ = 9;
      stan::model::assign(omegas,
        stan::math::elt_multiply(
          stan::model::rvalue(vs, "vs",
            stan::model::index_min_max(2, (H - 1))),
          stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
            stan::model::index_min_max(1, (H - 2)))),
        "assigning variable omegas", stan::model::index_min_max(2, (H - 1)));
      current_statement__ = 10;
      stan::model::assign(omegas,
        stan::model::rvalue(cumprod_one_mv, "cumprod_one_mv",
          stan::model::index_uni((H - 1))),
        "assigning variable omegas", stan::model::index_uni(H));
      current_statement__ = 5;
      stan::math::check_simplex(function__, "omegas", omegas);
      if (emit_transformed_parameters__) {
        out__.write(omegas);
        out__.write(cumprod_one_mv);
      } 
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      } 
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // write_array_impl() 
    
  template <typename VecVar, typename VecI, 
  stan::require_vector_t<VecVar>* = nullptr, 
  stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr> 
  inline void transform_inits_impl(VecVar& params_r__, VecI& params_i__,
                                   VecVar& vars__,
                                   std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      local_scalar_t__ alpha = DUMMY_VAR__;
      alpha = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, alpha);
      local_scalar_t__ sigma2 = DUMMY_VAR__;
      sigma2 = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma2);
      Eigen::Matrix<local_scalar_t__, -1, -1> betas =
         Eigen::Matrix<local_scalar_t__, -1, -1>::Constant(betas_1dim__, H,
           DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          stan::model::assign(betas, in__.read<local_scalar_t__>(),
            "assigning variable betas", stan::model::index_uni(sym2__),
                                          stan::model::index_uni(sym1__));
        }
      }
      out__.write(betas);
      Eigen::Matrix<local_scalar_t__, -1, 1> vs =
         Eigen::Matrix<local_scalar_t__, -1, 1>::Constant(vs_1dim__,
           DUMMY_VAR__);
      for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
        stan::model::assign(vs, in__.read<local_scalar_t__>(),
          "assigning variable vs", stan::model::index_uni(sym1__));
      }
      out__.write_free_lub(0, 1, vs);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    } // transform_inits_impl() 
    
  inline void get_param_names(std::vector<std::string>& names__) const {
    
    names__ = std::vector<std::string>{"alpha", "sigma2", "betas", "vs",
      "omegas", "cumprod_one_mv"};
    
    } // get_param_names() 
    
  inline void get_dims(std::vector<std::vector<size_t>>& dimss__) const {
    
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{},
      std::vector<size_t>{},
      std::vector<size_t>{static_cast<size_t>(betas_1dim__),
                          static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(vs_1dim__)},
      std::vector<size_t>{static_cast<size_t>(H)},
      std::vector<size_t>{static_cast<size_t>(cumprod_one_mv_1dim__)}};
    
    } // get_dims() 
    
  inline void constrained_param_names(
                                      std::vector<std::string>& param_names__,
                                      bool emit_transformed_parameters__ = true,
                                      bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "sigma2");
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "vs" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "omegas" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= cumprod_one_mv_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cumprod_one_mv" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // constrained_param_names() 
    
  inline void unconstrained_param_names(
                                        std::vector<std::string>& param_names__,
                                        bool emit_transformed_parameters__ = true,
                                        bool emit_generated_quantities__ = true) const
    final {
    
    param_names__.emplace_back(std::string() + "alpha");
    param_names__.emplace_back(std::string() + "sigma2");
    for (int sym1__ = 1; sym1__ <= H; ++sym1__) {
      {
        for (int sym2__ = 1; sym2__ <= betas_1dim__; ++sym2__) {
          {
            param_names__.emplace_back(std::string() + "betas" + '.' + std::to_string(sym2__) + '.' + std::to_string(sym1__));
          } 
        }
      } 
    }
    for (int sym1__ = 1; sym1__ <= vs_1dim__; ++sym1__) {
      {
        param_names__.emplace_back(std::string() + "vs" + '.' + std::to_string(sym1__));
      } 
    }
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= (H - 1); ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "omegas" + '.' + std::to_string(sym1__));
        } 
      }
      for (int sym1__ = 1; sym1__ <= cumprod_one_mv_1dim__; ++sym1__) {
        {
          param_names__.emplace_back(std::string() + "cumprod_one_mv" + '.' + std::to_string(sym1__));
        } 
      }
    }
    
    if (emit_generated_quantities__) {
      
    }
    
    } // unconstrained_param_names() 
    
  inline std::string get_constrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(betas_1dim__) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"vs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(vs_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"omegas\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(H) + "},\"block\":\"transformed_parameters\"},{\"name\":\"cumprod_one_mv\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(cumprod_one_mv_1dim__) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_constrained_sizedtypes() 
    
  inline std::string get_unconstrained_sizedtypes() const {
    
    return std::string("[{\"name\":\"alpha\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"sigma2\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"betas\",\"type\":{\"name\":\"matrix\",\"rows\":" + std::to_string(betas_1dim__) + ",\"cols\":" + std::to_string(H) + "},\"block\":\"parameters\"},{\"name\":\"vs\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(vs_1dim__) + "},\"block\":\"parameters\"},{\"name\":\"omegas\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string((H - 1)) + "},\"block\":\"transformed_parameters\"},{\"name\":\"cumprod_one_mv\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(cumprod_one_mv_1dim__) + "},\"block\":\"transformed_parameters\"}]");
    
    } // get_unconstrained_sizedtypes() 
    
  
    // Begin method overload boilerplate
    template <typename RNG>
    inline void write_array(RNG& base_rng,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                            Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                            const bool emit_transformed_parameters = true,
                            const bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((1 + 1) + (betas_1dim__ * H)) + vs_1dim__);
      const size_t num_transformed = emit_transformed_parameters * 
  (H + cumprod_one_mv_1dim__);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      std::vector<int> params_i;
      vars = Eigen::Matrix<double, Eigen::Dynamic, 1>::Constant(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <typename RNG>
    inline void write_array(RNG& base_rng, std::vector<double>& params_r,
                            std::vector<int>& params_i,
                            std::vector<double>& vars,
                            bool emit_transformed_parameters = true,
                            bool emit_generated_quantities = true,
                            std::ostream* pstream = nullptr) const {
      const size_t num_params__ = 
  (((1 + 1) + (betas_1dim__ * H)) + vs_1dim__);
      const size_t num_transformed = emit_transformed_parameters * 
  (H + cumprod_one_mv_1dim__);
      const size_t num_gen_quantities = emit_generated_quantities * 0;
      const size_t num_to_write = num_params__ + num_transformed +
        num_gen_quantities;
      vars = std::vector<double>(num_to_write,
        std::numeric_limits<double>::quiet_NaN());
      write_array_impl(base_rng, params_r, params_i, vars,
        emit_transformed_parameters, emit_generated_quantities, pstream);
    }

    template <bool propto__, bool jacobian__, typename T_>
    inline T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
                       std::ostream* pstream = nullptr) const {
      Eigen::Matrix<int, -1, 1> params_i;
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }

    template <bool propto__, bool jacobian__, typename T__>
    inline T__ log_prob(std::vector<T__>& params_r,
                        std::vector<int>& params_i,
                        std::ostream* pstream = nullptr) const {
      return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
    }


    inline void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream = nullptr) const final {
      std::vector<double> params_r_vec(params_r.size());
      std::vector<int> params_i;
      transform_inits(context, params_i, params_r_vec, pstream);
      params_r = Eigen::Map<Eigen::Matrix<double,Eigen::Dynamic,1>>(
        params_r_vec.data(), params_r_vec.size());
    }

  inline void transform_inits(const stan::io::var_context& context,
                              std::vector<int>& params_i,
                              std::vector<double>& vars,
                              std::ostream* pstream__ = nullptr) const {
     constexpr std::array<const char*, 4> names__{"alpha", "sigma2", "betas",
      "vs"};
      const std::array<Eigen::Index, 4> constrain_param_sizes__{1, 1,
       (betas_1dim__ * H), vs_1dim__};
      const auto num_constrained_params__ = std::accumulate(
        constrain_param_sizes__.begin(), constrain_param_sizes__.end(), 0);
    
     std::vector<double> params_r_flat__(num_constrained_params__);
     Eigen::Index size_iter__ = 0;
     Eigen::Index flat_iter__ = 0;
     for (auto&& param_name__ : names__) {
       const auto param_vec__ = context.vals_r(param_name__);
       for (Eigen::Index i = 0; i < constrain_param_sizes__[size_iter__]; ++i) {
         params_r_flat__[flat_iter__] = param_vec__[i];
         ++flat_iter__;
       }
       ++size_iter__;
     }
     vars.resize(num_params_r__);
     transform_inits_impl(params_r_flat__, params_i, vars, pstream__);
    } // transform_inits() 
    
};
}

using stan_model = SimpleModel_NoRandomEffect_model_namespace::SimpleModel_NoRandomEffect_model;

#ifndef USING_R

// Boilerplate
stan::model::model_base& new_model(
        stan::io::var_context& data_context,
        unsigned int seed,
        std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}

stan::math::profile_map& get_stan_profile_data() {
  return SimpleModel_NoRandomEffect_model_namespace::profiles__;
}

#endif


